# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NetT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking', '~> 3.2.1'
    pod 'ReactiveObjC', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 1.1.0'

  # Pods for NetT

end
